### ISSUE TITLE
No admin table ?

### ISSUE THREAD

**Issue by ronrun** [klaravel/ntrust#34] opened 2017-05-08 14:20 UTC
After installed, some tables are added to the database, but no admins. I see \config\ntrust.php has 
'table' => 'admins',
model' => 'App\Models\Admin',

In your migrations file xxx_admin_ntrust_setup_tables.php, there is admin_permission_role, admin_permissions, admin_role_user, admin_roles. But no admins ??

**Comment by ajmerainfo** [comment] 2017-05-08 15:13
@ronrun 

Admin table you have to create your own. You can duplicate of users table like below.

```
Schema::create('admins', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('email')->unique();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });
```

**Comment by ronrun** [comment] 2017-05-08 16:56
ok, thank you.

**Closed as completed** 2017-05-08 17:51 UTC
